#!/bin/bash

prompt="$1"
apikey="sk-00000000000000000000000"


headers=(
  "Authorization: Bearer $apikey"
  "Content-Type: application/json"
)

data='{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "'"$prompt"'"}]
}'



response=$(curl -s -X POST -H "${headers[0]}" -H "${headers[1]}" -d "$data" https://api.openai.com/v1/chat/completions)

#echo "$response"
#completion_text=$(echo "$response" | jq -r '.choices[0].text')
content=$(echo $response | jq -r '.choices[].message.content')
echo "$content"
#echo "$completion_text"
